version: "3"
services:
  postgres:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - bbsays_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret-password
      POSTGRES_DB: bbsays
volumes:
  bbsays_data:
  # docker-compose down --remove-orphans --volumes